services:
  - type: web
    name: realtime-gantt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rtg_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      - key: PUSHER_APP_ID
        sync: false
      - key: PUSHER_KEY
        sync: false
      - key: PUSHER_SECRET
        sync: false
      - key: PUSHER_CLUSTER
        value: mt1
      - key: DATABASE_URL
        sync: false