services:
  - type: web
    name: realtime-gantt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rtg_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .